name: CD - Deploy to AWS

on:
  push:
    branches: [ release ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Login to Amazon ECR Public
        run: aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPO }} .
          docker tag ${{ secrets.ECR_REPO }}:latest ${{ secrets.ECR_URI }}
          docker push ${{ secrets.ECR_URI }}
  

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: monew-task-service
          cluster: monew-cluster
          wait-for-service-stability: true

      # Prometheus 전용 이미지 빌드 & ECR 푸시
      - name: Configure AWS Credentials for Prometheus
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR (Prometheus)
        run: |
          aws ecr get-login-password --region ap-northeast-2 | \
          docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build Prometheus Docker Image
        run: |
          docker build -t prom-custom ./prometheus
          docker tag prom-custom $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/monew-prometheus:latest

      - name: Push Prometheus Image to ECR
        run: |
          docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/monew-prometheus:latest